"""Compatibility wrapper for Telegram imports.

Shared implementation lives in `services.numbers.shared.temp_order`.
"""

from services.numbers.shared.temp_order import (  # noqa: F401
    TEMP_CANCEL_AFTER_SEC,
    TEMP_POLL_INTERVALS,
    TEMP_PROVIDER_SAFETY_BUFFER_SEC,
    TEMP_REFRESH_COOLDOWN_SEC,
    TEMP_REFUND_RETRY_WINDOW_SEC,
    TEMP_REUSE_WARRANTY_FALLBACK_SEC,
    TEMP_REUSE_WARRANTY_SEC_BY_PROVIDER,
    TEMP_WAIT_TIMEOUT_SEC,
    _as_float,
    _as_int,
    _bool_text,
    _clean_provider_error_text,
    _coerce_utc_datetime,
    _country_display_name,
    _extract_explicit_reuse_warranty_sec,
    _extract_new_sms_code,
    _extract_provider_wait_timeout_sec,
    _format_number_for_copy_html,
    _format_number_for_copy_text,
    _format_wait_time_short,
    _is_expected_provider_failure,
    _is_retryable_provider_cancel,
    _is_temp_order_active_for_trust_gate,
    _normalize_warranty_sec,
    _order_reuse_warranty_sec,
    _order_temp_timeout_sec,
    _parse_provider_dt,
    _poll_interval_for_provider,
    _provider_default_reuse_warranty_sec,
    _provider_error_text,
    _resolve_reuse_warranty_sec,
    _safe_code_text,
    _seconds_between,
    _seconds_from_text,
    _seconds_left_until,
    _seconds_until_timestamp,
    _split_number_for_copy,
    _temp_code_received_text,
    _temp_elapsed_sec,
    _temp_order_has_received_code,
    _temp_refresh_cooldown_left,
    _temp_reuse_policy_text,
    _temp_waiting_text,
    _to_utc_datetime,
    _utc_now,
    _warranty_minutes_text_value,
)
