from __future__ import annotations

SECTION_TABLE: tuple[dict[str, object], ...] = (
    {
        "key": "games",
        "label": {"en": "Games", "ar": "قسم الألعاب"},
        "aliases": ("games", "game", "قسم الالعاب", "قسم الألعاب"),
    },
    {
        "key": "chat_apps",
        "label": {"en": "Chat Apps", "ar": "قسم تطبيقات الدردشة"},
        "aliases": ("chat apps", "chat", "applications", "قسم التطبيقات", "تطبيقات الدردشة"),
    },
    {
        "key": "communications_data",
        "label": {"en": "Communications & Data", "ar": "قسم الاتصالات والبيانات"},
        "aliases": ("communications", "telecom", "data", "قسم الاتصالات والبيانات"),
    },
    {
        "key": "numbers_services",
        "label": {"en": "Numbers Services", "ar": "قسم خدمات الأرقام"},
        "aliases": ("numbers", "otp", "sms", "قسم خدمات الأرقام", "خدمات الارقام"),
    },
    {
        "key": "paid_subscriptions",
        "label": {"en": "Paid Subscriptions", "ar": "قسم الاشتراكات المدفوعة"},
        "aliases": ("subscriptions", "premium", "قسم الاشتراكات المدفوعة"),
    },
    {
        "key": "store_cards",
        "label": {"en": "Store Cards", "ar": "قسم بطاقات المتاجر الإلكترونية"},
        "aliases": ("store cards", "gift cards", "قسم بطاقات المتاجر الالكترونية", "قسم بطاقات المتاجر الإلكترونية"),
    },
    {
        "key": "internet_providers",
        "label": {"en": "Internet Providers", "ar": "قسم مزودات الأنترنت"},
        "aliases": ("internet providers", "wifi", "fiber", "قسم مزودات الأنترنت", "قسم مزودات الانترنت"),
    },
    {
        "key": "paid_apps",
        "label": {"en": "Paid Apps", "ar": "قسم التطبيقات المدفوعة"},
        "aliases": ("paid apps", "unlock tool", "قسم التطبيقات المدفوعة"),
    },
)


FAMILY_TABLE: dict[str, tuple[dict[str, object], ...]] = {
    "games": (
        {"key": "pubg", "label": "PUBG", "aliases": ("pubg", "pubgm", "ببجي", "شدات ببجي", "ببجي روبوت", "اضافات ببجي", "ببجي تركية", "new state")},
        {"key": "free_fire", "label": "Free Fire", "aliases": ("free fire", "freefire", "فري فاير", "garena free fire", "free fire memberships", "free fire europe")},
        {"key": "mobile_legends", "label": "Mobile Legends", "aliases": ("mobile legends", "mlbb", "موبايل ليجند", "mobile legends adventure", "magic chess gogo")},
        {"key": "league_of_legends", "label": "League of Legends", "aliases": ("league of legends", "riot points", "lol", "teamfight tactics")},
        {"key": "legends_of_runeterra", "label": "Legends of Runeterra", "aliases": ("legends of runeterra",)},
        {"key": "valorant", "label": "Valorant", "aliases": ("valorant",)},
        {"key": "call_of_duty", "label": "Call of Duty", "aliases": ("call of duty", "cod mobile")},
        {"key": "clash_of_clans", "label": "Clash of Clans", "aliases": ("clash of clans", "coc")},
        {"key": "honor_of_kings", "label": "Honor of Kings", "aliases": ("honor of kings", "honor of king", "hok")},
        {"key": "genshin_impact", "label": "Genshin Impact", "aliases": ("genshin impact", "genshin")},
        {"key": "delta_force", "label": "Delta Force", "aliases": ("delta force", "garena deltaforce", "garena delta force")},
        {"key": "blood_strike", "label": "Blood Strike", "aliases": ("blood strike",)},
        {"key": "brawl_stars", "label": "Brawl Stars", "aliases": ("brawel star", "brawl star", "brawl stars")},
        {"key": "whiteout_survival", "label": "Whiteout Survival", "aliases": ("whiteout survival",)},
        {"key": "war_robots", "label": "War Robots", "aliases": ("war robots",)},
        {"key": "yalla_ludo", "label": "Yalla Ludo", "aliases": ("yalla ludo", "يلا لودو")},
        {"key": "jawaker", "label": "Jawaker", "aliases": ("jawaker", "جواكر")},
        {"key": "eafc_mobile", "label": "EAFC Mobile", "aliases": ("eafc", "eafc mobile", "eafc 24", "فيفا موبايل", "fc mobile")},
        {"key": "lords_mobile", "label": "Lords Mobile", "aliases": ("lords mobile", "لوردس موبايل")},
        {"key": "super_sus", "label": "Super SUS", "aliases": ("super sus",)},
        {"key": "8_ball_pool", "label": "8 Ball Pool", "aliases": ("8 ball pool", "بيلياردو")},
        {"key": "fortnite", "label": "Fortnite", "aliases": ("fortnite", "فورت نايت")},
        {"key": "we_play", "label": "We Play", "aliases": ("we play",)},
        {"key": "revenge_of_the_sultans", "label": "Revenge Of The Sultans", "aliases": ("revenge of the sultans",)},
        {"key": "aya", "label": "Aya", "aliases": ("aya",)},
        {"key": "waki_star", "label": "Waki Star", "aliases": ("waki star",)},
        {"key": "soul_star", "label": "Soul Star", "aliases": ("soul star",)},
        {"key": "soul_shell", "label": "Soul Shell", "aliases": ("soul shell",)},
        {"key": "party_star", "label": "Party Star", "aliases": ("party star",)},
        {"key": "honey_jar", "label": "Honey Jar", "aliases": ("honey jar",)},
    ),
    "store_cards": (
        {"key": "apple_itunes", "label": "Apple / iTunes", "aliases": ("itunes", "apple", "i tunes", "ايتونز")},
        {"key": "steam", "label": "Steam", "aliases": ("steam", "ستيم")},
        {"key": "google_play", "label": "Google Play", "aliases": ("google play", "google turkish", "جوجل بلاي")},
        {"key": "playstation", "label": "PlayStation", "aliases": ("playstation", "psn", "بلاي ستيشن")},
        {"key": "razer_gold", "label": "Razer Gold", "aliases": ("razer", "razer gold")},
        {"key": "visa", "label": "Visa", "aliases": ("visa",)},
        {"key": "xbox", "label": "Xbox", "aliases": ("xbox",)},
        {"key": "nintendo", "label": "Nintendo", "aliases": ("nintendo",)},
        {"key": "roblox", "label": "Roblox", "aliases": ("roblox", "روبلوكس")},
        {"key": "discord", "label": "Discord", "aliases": ("discord",)},
        {"key": "imo", "label": "IMO", "aliases": ("imo",)},
    ),
    "paid_subscriptions": (
        {"key": "netflix", "label": "Netflix", "aliases": ("netflix",)},
        {"key": "shahid", "label": "Shahid", "aliases": ("shahid", "tv shahid")},
        {"key": "canva", "label": "Canva", "aliases": ("canva", "canva pro")},
        {"key": "telegram_premium", "label": "Telegram Premium", "aliases": ("telegram premium", "telegram star", "telegram stars", "اشتراك تلغرام")},
        {"key": "snapchat_plus", "label": "Snapchat+", "aliases": ("snapchat", "اشتراك سناب شات")},
        {"key": "youtube", "label": "YouTube", "aliases": ("youtube", "خدمات يوتيوب")},
        {"key": "chatgpt", "label": "ChatGPT", "aliases": ("chatgpt", "شات جي بيتي")},
    ),
    "communications_data": (
        {"key": "mtn", "label": "MTN", "aliases": ("mtn", "mtn رصيد")},
        {"key": "syriatel", "label": "Syriatel", "aliases": ("syriatel", "سيريتل", "رصيد سيريتل")},
        {"key": "sawa", "label": "SAWA", "aliases": ("sawa",)},
        {"key": "telecom_data", "label": "Telecom & Data", "aliases": ("الرصيد والعملات", "رصيد", "اتصالات", "بيانات")},
    ),
    "numbers_services": (
        {"key": "telegram_numbers", "label": "Telegram Numbers", "aliases": ("ارقام تلجرام", "ارقام تلغرام", "telegram numbers")},
        {"key": "gmail_numbers", "label": "Gmail Numbers", "aliases": ("ارقام جيميل", "gmail numbers")},
        {"key": "tiktok_numbers", "label": "TikTok Numbers", "aliases": ("ارقام تيك توك", "tiktok numbers")},
        {"key": "imo_numbers", "label": "IMO Numbers", "aliases": ("ارقام ايمو", "imo numbers")},
        {"key": "snapchat_numbers", "label": "Snapchat Numbers", "aliases": ("ارقام سناب شات", "snapchat numbers")},
        {"key": "instagram_numbers", "label": "Instagram Numbers", "aliases": ("ارقام انستغرام", "instagram numbers")},
        {"key": "icloud_numbers", "label": "iCloud Numbers", "aliases": ("ارقام ايكلود", "icloud numbers")},
        {"key": "chatgpt_numbers", "label": "ChatGPT Numbers", "aliases": ("ارقام شات جي بيتي", "chatgpt numbers")},
    ),
    "internet_providers": (
        {"key": "pro_net", "label": "Pro Net", "aliases": ("pro net",)},
        {"key": "sama_net", "label": "Sama Net", "aliases": ("sama net",)},
        {"key": "view_net", "label": "View Net", "aliases": ("view net",)},
        {"key": "hifi_net", "label": "Hifi Net", "aliases": ("hifi net",)},
        {"key": "lazer_net", "label": "Lazer Net", "aliases": ("lazer net",)},
        {"key": "mts", "label": "MTS", "aliases": ("mts",)},
        {"key": "cards_m", "label": "Cards M", "aliases": ("cards  m", "cards m")},
        {"key": "linet", "label": "Linet", "aliases": ("linet",)},
    ),
    "paid_apps": (
        {"key": "android_amt", "label": "Android AMT", "aliases": ("android amt", "amt")},
        {"key": "dft_pro", "label": "DFT Pro", "aliases": ("dft pro",)},
        {"key": "eft_pro", "label": "EFT Pro", "aliases": ("eft pro",)},
        {"key": "unlock_tool", "label": "Unlock Tool", "aliases": ("unlock tool", "unlock", "انلوك")},
        {"key": "direct_activation", "label": "Direct Activation", "aliases": ("تفعيل مباشر", "direct activation")},
    ),
}
