from __future__ import annotations

SECTION_TABLE: tuple[dict[str, object], ...] = (
    {
        "key": "games",
        "label": {"en": "Games", "ar": "قسم الألعاب"},
        "aliases": ("games", "game", "قسم الالعاب", "قسم الألعاب"),
    },
    {
        "key": "chat_apps",
        "label": {"en": "Chat Apps", "ar": "قسم تطبيقات الدردشة"},
        "aliases": ("chat apps", "chat", "applications", "قسم التطبيقات", "تطبيقات الدردشة"),
    },
    {
        "key": "social_services",
        "label": {"en": "Followers Services", "ar": "قسم خدمات المتابعين"},
        "aliases": ("followers services", "social services", "قسم خدمات المتابعين", "خدمات المتابعين"),
    },
    {
        "key": "communications_data",
        "label": {"en": "Communications & Data", "ar": "قسم الاتصالات والبيانات"},
        "aliases": ("communications", "telecom", "data", "قسم الاتصالات والبيانات"),
    },
    {
        "key": "numbers_services",
        "label": {"en": "Numbers Services", "ar": "قسم خدمات الأرقام"},
        "aliases": ("numbers", "otp", "sms", "قسم خدمات الأرقام", "خدمات الارقام"),
    },
    {
        "key": "paid_subscriptions",
        "label": {"en": "Paid Subscriptions", "ar": "قسم الاشتراكات المدفوعة"},
        "aliases": ("subscriptions", "premium", "قسم الاشتراكات المدفوعة"),
    },
    {
        "key": "store_cards",
        "label": {"en": "Store Cards", "ar": "قسم بطاقات المتاجر الإلكترونية"},
        "aliases": ("store cards", "gift cards", "قسم بطاقات المتاجر الالكترونية", "قسم بطاقات المتاجر الإلكترونية"),
    },
    {
        "key": "internet_providers",
        "label": {"en": "Internet Providers", "ar": "قسم مزودات الأنترنت"},
        "aliases": ("internet providers", "wifi", "fiber", "قسم مزودات الأنترنت", "قسم مزودات الانترنت"),
    },
    {
        "key": "paid_apps",
        "label": {"en": "Paid Apps", "ar": "قسم التطبيقات المدفوعة"},
        "aliases": ("paid apps", "unlock tool", "قسم التطبيقات المدفوعة"),
    },
)


FAMILY_TABLE: dict[str, tuple[dict[str, object], ...]] = {
    "games": (
        {"key": "pubg", "label": "PUBG", "aliases": ("pubg", "pubgm", "ببجي", "شدات ببجي", "ببجي روبوت", "اضافات ببجي", "ببجي تركية", "new state")},
        {"key": "free_fire", "label": "Free Fire", "aliases": ("free fire", "freefire", "فري فاير", "garena free fire", "free fire memberships", "free fire europe")},
        {"key": "mobile_legends", "label": "Mobile Legends", "aliases": ("mobile legends", "mlbb", "موبايل ليجند", "magic chess gogo")},
        {"key": "mobile_legends_adventure", "label": "Mobile Legends Adventure", "aliases": ("mobile legends adventure",)},
        {"key": "league_of_legends", "label": "League of Legends", "aliases": ("league of legends", "riot points", "lol", "teamfight tactics")},
        {"key": "legends_of_runeterra", "label": "Legends of Runeterra", "aliases": ("legends of runeterra",)},
        {"key": "valorant", "label": "Valorant", "aliases": ("valorant",)},
        {"key": "call_of_duty", "label": "Call of Duty", "aliases": ("call of duty mobile", "call of duty", "cod mobile")},
        {"key": "clash_of_clans", "label": "Clash of Clans", "aliases": ("clash of clans", "coc")},
        {"key": "honor_of_kings", "label": "Honor of Kings", "aliases": ("honor of kings", "honor of king", "hok")},
        {"key": "genshin_impact", "label": "Genshin Impact", "aliases": ("genshin impact", "genshin")},
        {"key": "delta_force", "label": "Delta Force", "aliases": ("delta force", "garena deltaforce", "garena delta force")},
        {"key": "blood_strike", "label": "Blood Strike", "aliases": ("blood strike",)},
        {"key": "brawl_stars", "label": "Brawl Stars", "aliases": ("brawel star", "brawl star", "brawl stars")},
        {"key": "whiteout_survival", "label": "Whiteout Survival", "aliases": ("whiteout survival",)},
        {"key": "war_robots", "label": "War Robots", "aliases": ("war robots",)},
        {"key": "yalla_ludo", "label": "Yalla Ludo", "aliases": ("yalla ludo", "يلا لودو")},
        {"key": "jawaker", "label": "Jawaker", "aliases": ("jawaker", "جواكر")},
        {"key": "eafc_mobile", "label": "EAFC Mobile", "aliases": ("eafc mobile", "فيفا موبايل", "fc mobile")},
        {"key": "eafc_24", "label": "EAFC 24", "aliases": ("eafc 24",)},
        {"key": "lords_mobile", "label": "Lords Mobile", "aliases": ("lords mobile", "لوردس موبايل")},
        {"key": "super_sus", "label": "Super SUS", "aliases": ("super sus",)},
        {"key": "8_ball_pool", "label": "8 Ball Pool", "aliases": ("8 ball pool", "بيلياردو")},
        {"key": "fortnite", "label": "Fortnite", "aliases": ("fortnite", "فورت نايت")},
        {"key": "we_play", "label": "We Play", "aliases": ("we play",)},
        {"key": "revenge_of_the_sultans", "label": "Revenge Of The Sultans", "aliases": ("revenge of the sultans",)},
        {"key": "waki_star", "label": "Waki Star", "aliases": ("waki star",)},
        {"key": "legend_of_neverland", "label": "Legend of Neverland", "aliases": ("legend of neverland",)},
        {"key": "legend_of_the_phoenix", "label": "Legend of the Phoenix", "aliases": ("legend of the phoenix",)},
        {"key": "solo_leveling_arise", "label": "Solo Leveling: Arise", "aliases": ("solo leveling: arise", "solo leveling arise")},
        {"key": "etheria_restart", "label": "Etheria Restart", "aliases": ("etheria restart",)},
        {"key": "honkai_star_rail", "label": "Honkai Star Rail", "aliases": ("honkai star rail",)},
        {"key": "zenless_zone_zero", "label": "Zenless Zone Zero", "aliases": ("zenless zone zero",)},
        {"key": "racing_master", "label": "Racing Master", "aliases": ("racing master",)},
        {"key": "dragonheir_silent_gods", "label": "Dragonheir: Silent Gods", "aliases": ("dragonheir: silent gods",)},
        {"key": "devil_may_cry_peak_of_combat", "label": "Devil May Cry: Peak of Combat", "aliases": ("devil may cry: peak of combat",)},
        {"key": "bleach_soul_resonance", "label": "Bleach: Soul Resonance", "aliases": ("bleach: soul resonance",)},
        {"key": "frag_pro_shooter", "label": "Frag Pro Shooter", "aliases": ("frag pro shooter",)},
        {"key": "lord_of_the_rings_rise_to_war", "label": "Lord of the Rings: Rise to War", "aliases": ("lord of the rings: rise to war",)},
        {"key": "bullet_echo", "label": "Bullet Echo", "aliases": ("bullet echo",)},
        {"key": "ghost_story_love_destiny", "label": "Ghost Story Love Destiny", "aliases": ("ghost story love destiny",)},
        {"key": "knives_out", "label": "Knives Out", "aliases": ("knives out",)},
        {"key": "tarisland", "label": "Tarisland", "aliases": ("tarisland",)},
        {"key": "pixel_gun_3d", "label": "Pixel Gun 3D", "aliases": ("pixel gun 3d",)},
        {"key": "cats_crash_arena_turbo_stars", "label": "Cats: Crash Arena Turbo Stars", "aliases": ("cats: crash arena turbo stars",)},
        {"key": "revelation_infinite_journey", "label": "Revelation: Infinite Journey", "aliases": ("revelation: infinite journey",)},
        {"key": "dunk_city_dynasty", "label": "Dunk City Dynasty", "aliases": ("dunk city dynasty",)},
        {"key": "age_of_empire_mobile", "label": "Age of Empire Mobile", "aliases": ("age of empire mobile",)},
        {"key": "wild_rift", "label": "Wild Rift", "aliases": ("wild rift",)},
        {"key": "undawn", "label": "Undawn", "aliases": ("undawn", "garena undawn")},
        {"key": "star_resonance", "label": "Star Resonance", "aliases": ("star resonance",)},
        {"key": "sword_of_justice", "label": "Sword of Justice", "aliases": ("sword of justice", "sword of justice north")},
        {"key": "rainbow_six_mobile", "label": "Rainbow Six Mobile", "aliases": ("rainbow six mobile",)},
        {"key": "harry_potter_magic_awaken", "label": "Harry Potter: Magic Awaken", "aliases": ("harry potter: magic awaken",)},
        {"key": "once_human", "label": "Once Human", "aliases": ("once human",)},
        {"key": "eggy_party", "label": "Eggy Party", "aliases": ("eggy party",)},
        {"key": "haikyu_fly_high", "label": "Haikyu Fly High", "aliases": ("haikyu fly high",)},
        {"key": "age_of_magic", "label": "Age of Magic", "aliases": ("age of magic",)},
        {"key": "enhypen_world", "label": "Enhypen World", "aliases": ("enhypen world",)},
        {"key": "ragnarok_origin", "label": "Ragnarok Origin", "aliases": ("ragnarok origin",)},
        {"key": "path_to_nowhere", "label": "Path to Nowhere", "aliases": ("path to nowhere",)},
        {"key": "sky_children_of_the_light", "label": "Sky: Children of the Light", "aliases": ("sky children of the light",)},
        {"key": "moonlight_blade_m", "label": "Moonlight Blade M", "aliases": ("moonlight blade m",)},
        {"key": "goddess_of_victory_nikke", "label": "GOD: Nikke", "aliases": ("gov: nikke", "goddess of victory nikke")},
        {"key": "punishing_gray_raven", "label": "Punishing Gray Raven", "aliases": ("punishing gray raven",)},
        {"key": "crossfire_legend", "label": "Crossfire: Legend", "aliases": ("crossfire: legend",)},
        {"key": "love_nikki", "label": "Love Nikki", "aliases": ("love nikki",)},
        {"key": "arknight_endfield", "label": "Arknight: Endfield", "aliases": ("arknight: endfield",)},
        {"key": "identity_v", "label": "Identity V", "aliases": ("identity v", "identity v no receipt")},
        {"key": "shining_nikki", "label": "Shining Nikki", "aliases": ("shining nikki",)},
        {"key": "honkai_impact_3rd", "label": "Honkai Impact 3rd", "aliases": ("honkai impact 3rd",)},
        {"key": "acecraft", "label": "Acecraft", "aliases": ("acecraft",)},
        {"key": "farlight_84", "label": "Farlight 84", "aliases": ("farlight 84",)},
        {"key": "spring_valley", "label": "Spring Valley: Farm Adventures", "aliases": ("spring valley: farm adventures",)},
        {"key": "starmaker", "label": "StarMaker", "aliases": ("starmaker",)},
        {"key": "ragnarok_idle_adventure_plus", "label": "Ragnarok Idle Adventure Plus", "aliases": ("ragnarok idle adventure plus",)},
        {"key": "black_clover_m", "label": "Black Clover M", "aliases": ("black clover m",)},
        {"key": "arena_breakout", "label": "Arena Breakout", "aliases": ("arena breakout", "arena breakout infinite")},
        {"key": "oxide_survival_island", "label": "Oxide: Survival Island", "aliases": ("oxide: survival island",)},
        {"key": "zepeto", "label": "Zepeto", "aliases": ("zepeto",)},
        {"key": "watcher_of_realms", "label": "Watcher of Realms", "aliases": ("watcher of realms",)},
        {"key": "heartopia", "label": "Heartopia", "aliases": ("heartopia",)},
        {"key": "free_fire_memberships", "label": "Free Fire Memberships", "aliases": ("free fire memberships",)},
        {"key": "teen_patti_gold", "label": "Teen Patti Gold", "aliases": ("teen patti gold",)},
        {"key": "kings_choice", "label": "Kings Choice", "aliases": ("kings choice",)},
        {"key": "metal_slug_awakening", "label": "Metal Slug Awakening", "aliases": ("metal slug awakening",)},
        {"key": "dragon_nest_m_classic", "label": "Dragon Nest M: Classic", "aliases": ("dragon nest m: classic",)},
        {"key": "lifeafter", "label": "LifeAfter", "aliases": ("lifeafter",)},
        {"key": "where_winds_meet", "label": "Where Winds Meet", "aliases": ("where winds meet",)},
        {"key": "ragnarok_crush", "label": "Ragnarok Crush", "aliases": ("ragnarok crush",)},
        {"key": "ragnarok_x", "label": "Ragnarok X", "aliases": ("ragnarok x",)},
        {"key": "growtopia", "label": "Growtopia", "aliases": ("growtopia",)},
        {"key": "marvel_mystic_mayhem", "label": "Marvel Mystic Mayhem", "aliases": ("marvel mystic mayhem",)},
        {"key": "state_of_survival", "label": "State of Survival", "aliases": ("state of survival",)},
        {"key": "love_and_deepspace", "label": "Love and Deepspace", "aliases": ("love and deepspace",)},
        {"key": "blockman_go", "label": "Blockman Go", "aliases": ("blockman go",)},
        {"key": "hero_clash", "label": "Hero Clash", "aliases": ("hero clash",)},
        {"key": "dragon_raja", "label": "Dragon Raja", "aliases": ("dragon raja",)},
        {"key": "silver_and_blood", "label": "Silver and Blood", "aliases": ("silver and blood",)},
        {"key": "crossout_mobile", "label": "Crossout Mobile", "aliases": ("crossout mobile",)},
        {"key": "crystal_of_atlan", "label": "Crystal of Atlan", "aliases": ("crystal of atlan",)},
        {"key": "afk_journey", "label": "AFK Journey", "aliases": ("afk journey",)},
        {"key": "sausage_man", "label": "Sausage Man", "aliases": ("sausage man",)},
        {"key": "life_makeover", "label": "Life Makeover", "aliases": ("life makeover",)},
        {"key": "hatsune_miku", "label": "Hatsune Miku", "aliases": ("hatsune miku",)},
        {"key": "eve_echoes", "label": "EVE Echoes", "aliases": ("eve echoes",)},
        {"key": "heaven_burns_red", "label": "Heaven Burns Red", "aliases": ("heaven burns red",)},
        {"key": "t3_arena", "label": "T3 Arena", "aliases": ("t3 arena",)},
        {"key": "echocalypse_scarlet_covenant", "label": "Echocalypse: Scarlet Covenant", "aliases": ("echocalypse: scarlet covenant",)},
        {"key": "project_entropy", "label": "Project Entropy", "aliases": ("project entropy",)},
        {"key": "civilization_eras_allies", "label": "Civilization: Eras & Allies", "aliases": ("civilization: eras & allies",)},
        {"key": "deadly_dudes", "label": "Deadly Dudes", "aliases": ("deadly dudes",)},
        {"key": "rememento_white_shadows", "label": "Rememento: White Shadows", "aliases": ("rememento: white shadows",)},
        {"key": "marvel_duel", "label": "Marvel Duel", "aliases": ("marvel duel",)},
        {"key": "mecha_break", "label": "Mecha Break", "aliases": ("mecha break",)},
        {"key": "duet_night_abyss", "label": "Duet Night Abyss", "aliases": ("duet night abyss",)},
        {"key": "onmyoji_arena", "label": "Onmyoji Arena", "aliases": ("onmyoji arena",)},
        {"key": "arena_of_valor", "label": "Arena of Valor", "aliases": ("arena of valor",)},
        {"key": "destiny_rising", "label": "Destiny: Rising", "aliases": ("destiny: rising",)},
        {"key": "stumble_guys", "label": "Stumble Guys", "aliases": ("stumble guys",)},
        {"key": "wuthering_waves", "label": "Wuthering Waves", "aliases": ("wuthering waves",)},
        {"key": "maplestory_m", "label": "MapleStory M", "aliases": ("maplestory m",)},
        {"key": "snowbreak_containment_zone", "label": "Snowbreak: Containment Zone", "aliases": ("snowbreak containment zone",)},
        {"key": "marvel_rivals", "label": "Marvel Rivals", "aliases": ("marvel rivals",)},
        {"key": "my_singing_monsters", "label": "My Singing Monsters", "aliases": ("my singing monsters",)},
        {"key": "asphalt_9_legends", "label": "Asphalt 9: Legends", "aliases": ("asphalt 9: legends",)},
        {"key": "kingshot", "label": "Kingshot", "aliases": ("kingshot",)},
        {"key": "azur_lane", "label": "Azur Lane", "aliases": ("azur lane",)},
        {"key": "stormshot", "label": "Stormshot", "aliases": ("stormshot",)},
        {"key": "tiles_survive", "label": "Tiles Survive", "aliases": ("tiles survive",)},
        {"key": "sea_of_conquest", "label": "Sea of Conquest", "aliases": ("sea of conquest",)},
    ),
    "chat_apps": (
        {"key": "honey_jar", "label": "Honey Jar", "aliases": ("honey jar",)},
        {"key": "party_star", "label": "Party Star", "aliases": ("party star",)},
        {"key": "soul_shell", "label": "Soul Shell", "aliases": ("soul shell",)},
        {"key": "soul_star", "label": "Soul Star", "aliases": ("soul star",)},
    ),
    "social_services": (
        {"key": "tiktok_services", "label": "TikTok Services", "aliases": ("خدمات تيك توك", "tiktok services", "tiktok")},
        {"key": "whatsapp_services", "label": "WhatsApp Services", "aliases": ("خدمات وتس اب", "whatsapp services", "whatsapp")},
        {"key": "facebook_services", "label": "Facebook Services", "aliases": ("خدمات الفيسبوك", "facebook services", "facebook")},
        {"key": "telegram_services", "label": "Telegram Services", "aliases": ("خدمات تلجرام", "خدمات تلغرام", "telegram services")},
        {"key": "instagram_services", "label": "Instagram Services", "aliases": ("خدمات انستغرام", "instagram services", "instagram")},
        {"key": "kik_services", "label": "Kik Services", "aliases": ("خدمات كيك", "kik services", "kik")},
        {"key": "youtube_services", "label": "YouTube Services", "aliases": ("خدمات يوتيوب", "youtube services")},
    ),
    "store_cards": (
        {"key": "apple_itunes", "label": "Apple / iTunes", "aliases": ("itunes", "apple", "i tunes", "ايتونز")},
        {"key": "steam", "label": "Steam", "aliases": ("steam", "ستيم")},
        {"key": "google_play", "label": "Google Play", "aliases": ("google play", "google turkish", "جوجل بلاي")},
        {"key": "playstation", "label": "PlayStation", "aliases": ("playstation", "psn", "بلاي ستيشن")},
        {"key": "razer_gold", "label": "Razer Gold", "aliases": ("razer", "razer gold")},
        {"key": "visa", "label": "Visa", "aliases": ("visa",)},
        {"key": "xbox", "label": "Xbox", "aliases": ("xbox",)},
        {"key": "nintendo", "label": "Nintendo", "aliases": ("nintendo",)},
    ),
    "paid_subscriptions": (
        {"key": "netflix", "label": "Netflix", "aliases": ("netflix",)},
        {"key": "shahid", "label": "Shahid", "aliases": ("shahid", "tv shahid")},
        {"key": "canva", "label": "Canva", "aliases": ("canva", "canva pro")},
        {"key": "telegram_premium", "label": "Telegram Premium", "aliases": ("telegram premium", "telegram star", "telegram stars", "اشتراك تلغرام")},
        {"key": "snapchat_plus", "label": "Snapchat+", "aliases": ("snapchat", "اشتراك سناب شات")},
        {"key": "youtube", "label": "YouTube", "aliases": ("youtube", "خدمات يوتيوب")},
        {"key": "chatgpt", "label": "ChatGPT", "aliases": ("chatgpt", "شات جي بيتي")},
    ),
    "communications_data": (
        {"key": "aya", "label": "Aya", "aliases": ("aya",)},
        {"key": "mtn", "label": "MTN", "aliases": ("mtn", "mtn رصيد")},
        {"key": "syriatel", "label": "Syriatel", "aliases": ("syriatel", "سيريتل", "رصيد سيريتل")},
        {"key": "sawa", "label": "SAWA", "aliases": ("sawa",)},
        {"key": "telecom_data", "label": "Telecom & Data", "aliases": ("الرصيد والعملات", "رصيد", "اتصالات", "بيانات")},
    ),
    "numbers_services": (
        {"key": "telegram_numbers", "label": "Telegram Numbers", "aliases": ("ارقام تلجرام", "ارقام تلغرام", "telegram numbers")},
        {"key": "gmail_numbers", "label": "Gmail Numbers", "aliases": ("ارقام جيميل", "gmail numbers")},
        {"key": "tiktok_numbers", "label": "TikTok Numbers", "aliases": ("ارقام تيك توك", "tiktok numbers")},
        {"key": "imo_numbers", "label": "IMO Numbers", "aliases": ("ارقام ايمو", "imo numbers")},
        {"key": "snapchat_numbers", "label": "Snapchat Numbers", "aliases": ("ارقام سناب شات", "snapchat numbers")},
        {"key": "instagram_numbers", "label": "Instagram Numbers", "aliases": ("ارقام انستغرام", "instagram numbers")},
        {"key": "icloud_numbers", "label": "iCloud Numbers", "aliases": ("ارقام ايكلود", "icloud numbers")},
        {"key": "chatgpt_numbers", "label": "ChatGPT Numbers", "aliases": ("ارقام شات جي بيتي", "chatgpt numbers")},
    ),
    "internet_providers": (
        {"key": "pro_net", "label": "Pro Net", "aliases": ("pro net",)},
        {"key": "sama_net", "label": "Sama Net", "aliases": ("sama net",)},
        {"key": "view_net", "label": "View Net", "aliases": ("view net",)},
        {"key": "hifi_net", "label": "Hifi Net", "aliases": ("hifi net",)},
        {"key": "lazer_net", "label": "Lazer Net", "aliases": ("lazer net",)},
        {"key": "mts", "label": "MTS", "aliases": ("mts",)},
        {"key": "cards_m", "label": "Cards M", "aliases": ("cards  m", "cards m")},
        {"key": "linet", "label": "Linet", "aliases": ("linet",)},
    ),
    "paid_apps": (
        {"key": "android_amt", "label": "Android AMT", "aliases": ("android amt", "amt")},
        {"key": "dft_pro", "label": "DFT Pro", "aliases": ("dft pro",)},
        {"key": "eft_pro", "label": "EFT Pro", "aliases": ("eft pro",)},
        {"key": "unlock_tool", "label": "Unlock Tool", "aliases": ("unlock tool", "unlock", "انلوك")},
        {"key": "direct_activation", "label": "Direct Activation", "aliases": ("تفعيل مباشر", "direct activation")},
    ),
}
